### ISSUE TITLE
Segfault in RizinArchitecture::postSpecFile()::{lambda(rz_analysis_function_t*)#1}::operator()(rz_analysis_function_t*) const (core_ghidra.so)

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-ghidra#213]
Rizin commit: https://github.com/rizinorg/rizin/commit/a39c8e7e9ac39f6a9b0680b3d754aee1e63e1a15 (without https://github.com/rizinorg/rizin/commit/09082667580cb3e9fcbc4ba841e3e9943e1f1333 to avoid https://github.com/rizinorg/rz-ghidra/issues/212 )
RzGhidra commit: https://github.com/rizinorg/rz-ghidra/commit/7666c96e2120a57b1d81efa7d96ea75a6a9c32ce
```
[i] ℤ rizin filetime.c-clang-x64-O0.o                                                                                                                                                                                             19:41:57 
Warning: run rizin with -e io.cache=true to fix relocations in disassembly
 -- Use hasher to calculate hashes of portion blocks of a file
[0x08000040]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[Fail to load 32 bytes of data at 0x08000820
Fail to load 32 bytes of data at 0x0800080e
Fail to load 32 bytes of data at 0x08000811
Fail to load 32 bytes of data at 0x0800081c
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x08000040]> s sym.showVersion
[0x08000610]> pdf
            ; CALL XREF from sym.main @ 0x80000b0
╭ sym.showVersion ();
│           0x08000610      push  rbp
│           0x08000611      mov   rbp, rsp
│           0x08000614      mov   edi, 1
│           0x08000619      movabs rsi, 0                              ; RELOC 64 .rodata.str1.1 @ 0x08000636 + 0xd1
│           0x08000623      mov   eax, 0x11d                           ; 285
│           0x08000628      mov   edx, eax
│           0x0800062a      call  sym.Vwrite
│           0x0800062f      xor   edi, edi
╰           0x08000631      call  exit                                 ; RELOC 32 exit
[0x08000610]> pdg
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1444951==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000008c (pc 0x7fa536446419 bp 0x7ffeff34d2c0 sp 0x7ffeff34d280 T0)
==1444951==The signal is caused by a READ memory access.
==1444951==Hint: address points to the zero page.
    #0 0x7fa536446419 in RizinArchitecture::postSpecFile()::{lambda(rz_analysis_function_t*)#1}::operator()(rz_analysis_function_t*) const (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x490419)
    #1 0x7fa5364479dc in void rz_list_foreach_cpp<rz_analysis_function_t, RizinArchitecture::postSpecFile()::{lambda(rz_analysis_function_t*)#1}>(rz_list_t*, RizinArchitecture::postSpecFile()::{lambda(rz_analysis_function_t*)#1} const&) (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x4919dc)
    #2 0x7fa536446500 in RizinArchitecture::postSpecFile() (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x490500)
    #3 0x7fa5364a3d33 in Architecture::init(DocumentStorage&) (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x4edd33)
    #4 0x7fa53643bd0c in Decompile(rz_core_t*, unsigned long long, DecompileMode, std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&, rz_annotated_code_t**) (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x485d0c)
    #5 0x7fa53643c63f in DecompileCmd(rz_core_t*, DecompileMode) (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x48663f)
    #6 0x7fa53643d430 in pdg_handler(rz_core_t*, int, char const**) (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x487430)
    #7 0x7fa53c52227f in argv_call_cb ../librz/core/cmd_api.c:618
    #8 0x7fa53c5229af in call_cd ../librz/core/cmd_api.c:651
    #9 0x7fa53c522993 in call_cd ../librz/core/cmd_api.c:648
    #10 0x7fa53c522bfd in rz_cmd_call_parsed_args ../librz/core/cmd_api.c:669
    #11 0x7fa53c4f6070 in handle_ts_arged_command_internal ../librz/core/cmd.c:4623
    #12 0x7fa53c4f544f in handle_ts_arged_command ../librz/core/cmd.c:4585
    #13 0x7fa53c512029 in handle_ts_command ../librz/core/cmd.c:6054
    #14 0x7fa53c513691 in handle_ts_commands_internal ../librz/core/cmd.c:6111
    #15 0x7fa53c512858 in handle_ts_commands ../librz/core/cmd.c:6076
    #16 0x7fa53c51498b in core_cmd_tsr2cmd ../librz/core/cmd.c:6206
    #17 0x7fa53c515254 in rz_core_cmd ../librz/core/cmd.c:6253
    #18 0x7fa53c566bdb in rz_core_prompt_exec ../librz/core/core.c:2911
    #19 0x7fa53c564647 in rz_core_prompt_loop ../librz/core/core.c:2762
    #20 0x7fa549d2c045 in rz_main_rizin ../librz/main/rizin.c:1362
    #21 0x401a5c in main ../binrz/rizin/rizin.c:55
    #22 0x7fa5491551e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)
    #23 0x4011dd in _start (/home/akochkov/.local/bin/rizin+0x4011dd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/akochkov/.local/share/rizin/plugins/core_ghidra.so+0x490419) in RizinArchitecture::postSpecFile()::{lambda(rz_analysis_function_t*)#1}::operator()(rz_analysis_function_t*) const
==1444951==ABORTING
```
[filetime.c-clang-x64-O0.o.zip](https://github.com/rizinorg/rz-ghidra/files/6141553/filetime.c-clang-x64-O0.o.zip)

**Comment by XVilka** [comment]
I cannot reproduce it anymore after updating both Rizin and RzGhidra. Probably also related to the API change.
